// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model-generated tool input progress. Carries only UTF-8 byte counts, never arguments.
 * This is ephemeral display metadata, not authoritative usage or execution progress.
 */
export type ToolCallInputProgressNotification = { threadId: string, turnId: string, itemId: string, deltaBytes: number, };
